
   
version: "3.8"
services:
  neo4j:
    image: neo4j:4.4.3
    volumes:
      - type: bind
        source: ./data/neo4j/data
        target: /data
      - type: bind
        source: ./data/neo4j/logs
        target: /logs
      - type: bind
        source: ./data/neo4j/dump
        target: /dump
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    env_file: .env
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
